@echo off
REM Step 3: cURL test with exact path to prove auth context
REM Replace PUBLISHABLE_KEY and USER_ACCESS_TOKEN with actual values

echo Testing cURL upload with exact nested path...

REM You need to replace these values:
REM PUBLISHABLE_KEY: sb_publishable_en7oBtMUR3Ai1Jxa0Nt0hg_vWMrxSkM
REM USER_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiIsImtpZCI6IjNWdzQ5SzVURXRRZ0VnbjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL21rc2t0cHVqd3dydm5kaW5lbmNsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmNjZlYTZkNi1hMDg2LTRjNmMtYTJjYS1iNzVlYjA0OGRkYjAiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU4MjE4MDEwLCJpYXQiOjE3NTgyMTQ0MTAsImVtYWlsIjoiamRtb29uK3Rlc3Rmb3VuZGVyMTBAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImpkbW9vbit0ZXN0Zm91bmRlcjEwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJUZXN0IEZvdW5kZXIxMCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZjY2ZWE2ZDYtYTA4Ni00YzZjLWEyY2EtYjc1ZWIwNDhkZGIwIiwidXNlcl90eXBlIjoiZm91bmRlciJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU4MjE0NDEwfV0sInNlc3Npb25faWQiOiIzMDcyMWJkOS04NzY0LTQ1ZjItOWVlZS0zNmM4MWExZTRiOWIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.vew7HvXOI3XSNmNGiL9Nt_bPj3RUPzp0uidaS0oRYb8

curl -i -X POST ^
  "https://mksktpujwwrvndinencl.supabase.co/storage/v1/object/pitch-decks/7f30e44b-fb7e-48cb-9941-1c964cafc3a7/pitch-deck.pdf" ^
  -H "apikey: sb_publishable_en7oBtMUR3Ai1Jxa0Nt0hg_vWMrxSkM" ^
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IjNWdzQ5SzVURXRRZ0VnbjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL21rc2t0cHVqd3dydm5kaW5lbmNsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmNjZlYTZkNi1hMDg2LTRjNmMtYTJjYS1iNzVlYjA0OGRkYjAiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU4MjE4MDEwLCJpYXQiOjE3NTgyMTQ0MTAsImVtYWlsIjoiamRtb29uK3Rlc3Rmb3VuZGVyMTBAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImpkbW9vbit0ZXN0Zm91bmRlcjEwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJUZXN0IEZvdW5kZXIxMCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZjY2ZWE2ZDYtYTA4Ni00YzZjLWEyY2EtYjc1ZWIwNDhkZGIwIiwidXNlcl90eXBlIjoiZm91bmRlciJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU4MjE0NDEwfV0sInNlc3Npb25faWQiOiIzMDcyMWJkOS04NzY0LTQ1ZjItOWVlZS0zNmM4MWExZTRiOWIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.vew7HvXOI3XSNmNGiL9Nt_bPj3RUPzp0uidaS0oRYb8" ^
  -H "Content-Type: application/pdf" ^
  --data-binary "@test-file.pdf"

echo.
echo If successful, run this SQL to check for the new object:
echo SELECT id, bucket_id, name, owner, created_at FROM storage.objects WHERE bucket_id = 'pitch-decks' ORDER BY created_at DESC LIMIT 5;